"""add bakeries and baked_goods models

Revision ID: e67688ec5558
Revises: 1a660c242acb
Create Date: 2024-06-26 15:45:22.974854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67688ec5558'
down_revision = '1a660c242acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
